Update auto-release.yml
Signed-off-by: tmmymrtnz <63567408+tmmymrtnz@users.noreply.github.com>

diff --git a/.github/workflows/auto-release.yml b/.github/workflows/auto-release.yml
--- a/.github/workflows/auto-release.yml
+++ b/.github/workflows/auto-release.yml
@@ -42,7 +42,7 @@ jobs:
       run: |
         echo "Building Cilium for AMD64..."
         make clean
-        make NO_PRECHECK=1 GOARCH=amd64 VERBOSE=1 || { echo "Build failed for AMD64!"; exit 1; }
+        NO_PRECHECK=1 GOARCH=amd64 make VERBOSE=1 || { echo "Build failed for AMD64!"; exit 1; }
 
     # Step 6: Locate and Package Binary for AMD64
     - name: Locate and Package Cilium for AMD64
@@ -62,7 +62,7 @@ jobs:
       run: |
         echo "Building Cilium for ARM64..."
         make clean
-        make NO_PRECHECK=1 GOARCH=arm64 VERBOSE=1 || { echo "Build failed for ARM64!"; exit 1; }
+        NO_PRECHECK=1 GOARCH=arm64 make VERBOSE=1 || { echo "Build failed for ARM64!"; exit 1; }
 
     # Step 8: Locate and Package Binary for ARM64
     - name: Locate and Package Cilium for ARM64
